FROM golang:1.22

ARG ATLAS_URI
ARG FIREBASE_PROJECT_ID
ARG REDIS_URI
ARG REDIS_PASSWORD
ARG REDIS_USERNAME

ENV APP_HOME /go/src/authv2
ENV ATLAS_URI ${ATLAS_URI}
ENV REDIS_URI ${REDIS_URI}
ENV REDIS_PASSWORD ${REDIS_PASSWORD}
ENV REDIS_USERNAME ${REDIS_USERNAME}
ENV FIREBASE_PROJECT_ID ${FIREBASE_PROJECT_ID}
ENV GIN_MODE=release

WORKDIR "$APP_HOME"

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .
RUN go build -tags=jsoniter -o authv2 

EXPOSE 8080

CMD ["./authv2"]
